language: go
go:
  - 1.13.x

services:
  - docker

env:
  - GO111MODULE: "on"

stages:
  - build
  - name: release
    if: tag IS present
  - name: docker
    if: tag IS present

jobs:
  include:
    - stage: build
      script:
        - go mod vendor
        - go build -o pxc-checker ./
    - stage: release
      script:
        - go mod vendor
        - curl -sL https://git.io/goreleaser | bash -s - release
    - stage: docker
      script:
        - docker build -t larrabee/pxc-checker:${TRAVIS_TAG} .
        - docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_TOKEN}"
        - docker push larrabee/pxc-checker:${TRAVIS_TAG}
        - docker tag larrabee/pxc-checker:${TRAVIS_TAG} larrabee/pxc-checker:latest
        - docker push larrabee/pxc-checker:latest
